### ISSUE TITLE
Notifications are blank and take me to a blank screen

### ISSUE THREAD

**Issue by sidgames5** [FossifyOrg/Messages#102]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

CalyxOS 5.4.0 Android 14

### Affected device model

Pixel 4a 5G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Have someone send you a message in MMS group
2. Click on notification
3. See error

### Expected behavior

The notification should say who it is from and the content of the message. When clicking the notification it should open up to the group chat.

### Actual behavior

The notification is blank and when clicked on, it goes to a blank screen then gives an error. Most of the time I get the expected behavior and the error only happens occasionally.

### Additional information

This only happens in MMS groups. I am using AT&T.

**Comment by sidgames5** [comment]
It just says "An unknown error occurred"

**Comment by DeathTBO** [comment]
Just wanted to throw in that I also have this issue. I have a Galaxy S22, and have installed from FDroid. Unknown error when I attempt to view the blank message. Seems to happen sporadically, and only with my group chats.

**Comment by RogerGodzilla** [comment]
I am having an issue exactly as described on version 1.1.5 installed from fdroid on an S22 Ultra with stock firmware.

**Comment by sidgames5** [comment]
I may have found some useful logs:
```
2025-04-01 10:07:02.751 26707-26707 MmsReceivedReceiver     org.fossify.messages.debug           V  MMS has finished downloading, persisting it to the database
2025-04-01 10:07:02.753 26707-26707 MmsReceivedReceiver     org.fossify.messages.debug           V  /data/user/0/org.fossify.messages.debug/cache/download.7659700846323381877.dat
2025-04-01 10:07:02.776 26707-30027 MmsReceivedReceiver     org.fossify.messages.debug           V  No MMSC information set, so no notification tasks will be able to complete
2025-04-01 10:07:02.790 26707-30027 DownloadRequest         org.fossify.messages.debug           D  DownloadRequest.persistIfRequired
2025-04-01 10:07:03.004 26707-30027 MmsReceivedReceiver     org.fossify.messages.debug           V  response saved successfully
2025-04-01 10:07:03.005 26707-30027 MmsReceivedReceiver     org.fossify.messages.debug           V  response length: 871
2025-04-01 10:07:03.149 25465-27075 DatabaseUtils           android.process.acore                E  Writing exception to parcel
                                                                                                    java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: org.fossify.messages.debug, calling package:org.fossify.messages.debug
                                                                                                    	at com.android.providers.contacts.LegacyApiSupport.query(LegacyApiSupport.java:1838)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.queryLocal(ContactsProvider2.java:7502)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.queryDirectoryIfNecessary(ContactsProvider2.java:5882)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.queryInternal(ContactsProvider2.java:5727)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.query(ContactsProvider2.java:5672)
                                                                                                    	at android.content.ContentProvider.query(ContentProvider.java:1716)
                                                                                                    	at android.content.ContentProvider$Transport.query(ContentProvider.java:295)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1505)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1444)
2025-04-01 10:07:04.431 26707-26707 MmsReceivedReceiver     org.fossify.messages.debug           V  MMS has finished downloading, persisting it to the database
2025-04-01 10:07:04.432 26707-26707 MmsReceivedReceiver     org.fossify.messages.debug           V  /data/user/0/org.fossify.messages.debug/cache/download.1393717132868435200.dat
2025-04-01 10:07:04.443 26707-30042 MmsReceivedReceiver     org.fossify.messages.debug           V  No MMSC information set, so no notification tasks will be able to complete
2025-04-01 10:07:04.443 26707-30042 DownloadRequest         org.fossify.messages.debug           D  DownloadRequest.persistIfRequired
2025-04-01 10:07:04.638 26707-30042 MmsReceivedReceiver     org.fossify.messages.debug           V  response saved successfully
2025-04-01 10:07:04.638 26707-30042 MmsReceivedReceiver     org.fossify.messages.debug           V  response length: 895
2025-04-01 10:07:04.766 25465-27041 DatabaseUtils           android.process.acore                E  Writing exception to parcel
                                                                                                    java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: org.fossify.messages.debug, calling package:org.fossify.messages.debug
                                                                                                    	at com.android.providers.contacts.LegacyApiSupport.query(LegacyApiSupport.java:1838)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.queryLocal(ContactsProvider2.java:7502)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.queryDirectoryIfNecessary(ContactsProvider2.java:5882)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.queryInternal(ContactsProvider2.java:5727)
                                                                                                    	at com.android.providers.contacts.ContactsProvider2.query(ContactsProvider2.java:5672)
                                                                                                    	at android.content.ContentProvider.query(ContentProvider.java:1716)
                                                                                                    	at android.content.ContentProvider$Transport.query(ContentProvider.java:295)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1505)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1444)
2025-04-01 10:07:13.685 26707-29735 HWUI                    org.fossify.messages.debug           D  --- Failed to create image decoder with message 'unimplemented'
2025-04-01 10:07:15.438 26707-26717 .messages.debug         org.fossify.messages.debug           I  Background concurrent copying GC freed 5239KB AllocSpace bytes, 116(2320KB) LOS objects, 75% free, 9651KB/37MB, paused 214us,43us total 103.893ms
2025-04-01 10:07:15.490 26707-26719 System                  org.fossify.messages.debug           W  A resource failed to call release. 
2025-04-01 10:07:15.503 26707-29363 HWUI                    org.fossify.messages.debug           D  --- Failed to create image decoder with message 'unimplemented'
2025-04-01 10:07:15.507 26707-26719 System                  org.fossify.messages.debug           W  A resource failed to call CursorWrapperInner.close. 
2025-04-01 10:07:15.508 26707-26719 System                  org.fossify.messages.debug           W  A resource failed to call CursorWrapperInner.close. 
2025-04-01 10:07:19.554 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@174317059 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@4151e89
2025-04-01 10:07:19.718 26707-26744 Parcel                  org.fossify.messages.debug           W  Expecting binder but got null!
2025-04-01 10:07:19.791 26707-26707 RecyclerView            org.fossify.messages.debug           W  No adapter attached; skipping layout
2025-04-01 10:07:19.887 26707-26707 AssistStructure         org.fossify.messages.debug           I  Flattened final assist data: 3244 bytes, containing 1 windows, 20 views
2025-04-01 10:07:19.890 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@174317059 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@4151e89
2025-04-01 10:07:19.907 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@174317059 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@4151e89
2025-04-01 10:07:19.987 26707-26707 InsetsController        org.fossify.messages.debug           D  show(ime(), fromIme=true)
2025-04-01 10:07:20.046 26707-26707 Compatibil...geReporter org.fossify.messages.debug           D  Compat change id reported: 147798919; UID 10290; state: ENABLED
2025-04-01 10:07:20.245 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.246 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.246 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.246 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.247 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.247 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.248 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.248 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.260 26707-26707 Glide                   org.fossify.messages.debug           W  Load failed for [] with dimensions [126x126]
                                                                                                    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
2025-04-01 10:07:20.281 26707-26707 VRI[ThreadActivity]     org.fossify.messages.debug           D  visibilityChanged oldVisibility=true newVisibility=false
2025-04-01 10:07:20.287 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@3a1b334
2025-04-01 10:07:20.310 26707-26707 ImeTracker              org.fossify.messages.debug           I  org.fossify.messages.debug:3fdee09b: onShown
2025-04-01 10:07:20.373 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@174317059 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@f26ac08
2025-04-01 10:07:20.410 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@174317059 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@f26ac08
2025-04-01 10:07:20.411 26707-26707 InsetsController        org.fossify.messages.debug           D  hide(ime(), fromIme=true)
2025-04-01 10:07:20.423 26707-26707 ImeTracker              org.fossify.messages.debug           I  org.fossify.messages.debug:63c034a3: onCancelled at PHASE_CLIENT_ANIMATION_CANCEL
2025-04-01 10:07:20.423 26707-26707 ImeTracker              org.fossify.messages.debug           I  org.fossify.messages.debug:b3364f47: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_ON_ANIMATION_STATE_CHANGED fromUser false
2025-04-01 10:07:20.424 26707-26707 ImeTracker              org.fossify.messages.debug           I  org.fossify.messages.debug:b3364f47: onFailed at PHASE_CLIENT_VIEW_SERVED
2025-04-01 10:07:20.845 26707-26707 VRI[ThreadActivity]     org.fossify.messages.debug           D  visibilityChanged oldVisibility=true newVisibility=false
2025-04-01 10:07:20.864 26707-26707 WindowOnBackDispatcher  org.fossify.messages.debug           W  sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@58b235
2025-04-01 10:07:21.260 26707-29363 HWUI                    org.fossify.messages.debug           D  --- Failed to create image decoder with message 'unimplemented'
2025-04-01 10:07:21.452 26707-29735 HWUI                    org.fossify.messages.debug           D  --- Failed to create image decoder with message 'unimplemented'
2025-04-01 10:07:24.896 26707-26745 Parcel                  org.fossify.messages.debug           W  Expecting binder but got null!
2025-04-01 10:07:24.923 26707-26707 RecyclerView            org.fossify.messages.debug           W  No adapter attached; skipping layout
2025-04-01 10:07:25.451 26707-26707 VRI[MainActivity]       org.fossify.messages.debug           D  visibilityChanged oldVisibility=true newVisibility=false
2025-04-01 10:07:25.466 26707-26734 HWUI                    org.fossify.messages.debug           D  endAllActiveAnimators on 0xb400007ce8dd6660 (LayerDrawable) with handle 0xb400007cf8dda860
2025-04-01 10:07:25.658 26707-26707 ImeTracker              org.fossify.messages.debug           I  org.fossify.messages.debug:3c9a4f5f: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser true
2025-04-01 10:07:25.658 26707-26707 InputMethodManager      org.fossify.messages.debug           D  showSoftInput() view=org.fossify.commons.views.MyEditText{ab41850 VFED..CL. .F.P..ID 148,0-932,126 #7f090422 app:id/thread_type_message aid=1073741825} flags=0 reason=SHOW_SOFT_INPUT
2025-04-01 10:07:25.665 26707-26707 AssistStructure         org.fossify.messages.debug           I  Flattened final assist data: 3640 bytes, containing 1 windows, 23 views
2025-04-01 10:07:25.731 26707-26707 InsetsController        org.fossify.messages.debug           D  show(ime(), fromIme=true)
2025-04-01 10:07:25.903 26707-30134 HWUI                    org.fossify.messages.debug           D  --- Failed to create image decoder with message 'unimplemented'
2025-04-01 10:07:26.067 26707-26707 ImeTracker              org.fossify.messages.debug           I  org.fossify.messages.debug:3c9a4f5f: onShown```

**Comment by naveensingh** [comment]
Doesn't look related to this issue. 

My guess is that the blank screen is due to an ANR. If you are able to reproduce it reliably, you should see something like `Input dispatching timed out...` in the logs.

**Comment by sidgames5** [comment]
I printed out the mms body in the mms receiver and it printed out a message that was received properly but the next message got that blank notification.

![Image](https://github.com/user-attachments/assets/d3f17c83-bd8e-4484-b832-9310d3f93517)

![Image](https://github.com/user-attachments/assets/096845b9-03b6-457f-b37a-7115b1cae393)

**Comment by abrasmag3** [comment]
Bumping since I also experience this issue. Google Pixel 6a, GrapheneOS (Android 15), app version 1.1.7
