### ISSUE TITLE
Crash when opening strange group MMS

### ISSUE THREAD

**Issue by ThatOneCalculator** [FossifyOrg/Messages#95]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

GrapheneOS 14 Beta

### Affected device model

Google Pixel 7

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open conversation
2. Crash

### Expected behavior

This is a strange bugged conversation I have on my phone and I'm trying to find any app that can read it. It also crashes Google Messages, and crashes Fossify messages. 

### Actual behavior

```
type: logcat
osVersion: google/panther/panther:14/UQ1A.240205.002/2024020500:user/release-keys
packageName: org.fossify.messages:2
buffers: main,system,crash,events
level: error

--------- beginning of system
1707859748.803 31803 31803 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
1707859761.675 31803 31803 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
--------- beginning of crash
1707859761.757 31803 32097 E AndroidRuntime: FATAL EXCEPTION: Thread-22
1707859761.757 31803 32097 E AndroidRuntime: Process: org.fossify.messages, PID: 31803
1707859761.757 31803 32097 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodException: o8.c.<init> [class java.lang.String, class java.lang.String, class java.lang.String]
1707859761.757 31803 32097 E AndroidRuntime: 	at j8.e.a(SourceFile:117)
1707859761.757 31803 32097 E AndroidRuntime: 	at q8.a.c(SourceFile:37)
1707859761.757 31803 32097 E AndroidRuntime: 	at m8.h.l(SourceFile:8)
1707859761.757 31803 32097 E AndroidRuntime: 	at m8.c.y(SourceFile:40)
1707859761.757 31803 32097 E AndroidRuntime: 	at m8.c.x(SourceFile:1)
1707859761.757 31803 32097 E AndroidRuntime: 	at m8.c.p(SourceFile:16)
1707859761.757 31803 32097 E AndroidRuntime: 	at m8.c.c(SourceFile:160)
1707859761.757 31803 32097 E AndroidRuntime: 	at n8.c.c(SourceFile:1620)
1707859761.757 31803 32097 E AndroidRuntime: 	at y.t.a(SourceFile:217)
1707859761.757 31803 32097 E AndroidRuntime: 	at y.t.b(SourceFile:19)
1707859761.757 31803 32097 E AndroidRuntime: 	at s1.w.run(SourceFile:28)
1707859761.757 31803 32097 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
1707859761.757 31803 32097 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: o8.c.<init> [class java.lang.String, class java.lang.String, class java.lang.String]
1707859761.757 31803 32097 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:3325)
1707859761.757 31803 32097 E AndroidRuntime: 	at java.lang.Class.getDeclaredConstructor(Class.java:3063)
1707859761.757 31803 32097 E AndroidRuntime: 	at j8.e.a(SourceFile:86)
1707859761.757 31803 32097 E AndroidRuntime: 	... 11 more
--------- beginning of main
1707859763.083 32103 32103 E ossify.messages: Not starting debugger since process cannot load the jdwp agent.
1707859763.262 32103 32103 E cutils-trace: Error opening trace file: No such file or directory (2)
1707859763.458 32103 32103 E org.fossify.messages: Unable to find pattern file or unable to map it for am
1707859763.687 32103 32135 E cutils-trace: Error opening trace file: No such file or directory (2)
--------- switch to system
1707859763.703 32103 32103 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
1707859767.065 32103 32103 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
--------- switch to crash
1707859767.149 32103 32187 E AndroidRuntime: FATAL EXCEPTION: Thread-14
1707859767.149 32103 32187 E AndroidRuntime: Process: org.fossify.messages, PID: 32103
1707859767.149 32103 32187 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodException: o8.c.<init> [class java.lang.String, class java.lang.String, class java.lang.String]
1707859767.149 32103 32187 E AndroidRuntime: 	at j8.e.a(SourceFile:117)
1707859767.149 32103 32187 E AndroidRuntime: 	at q8.a.c(SourceFile:37)
1707859767.149 32103 32187 E AndroidRuntime: 	at m8.h.l(SourceFile:8)
1707859767.149 32103 32187 E AndroidRuntime: 	at m8.c.y(SourceFile:40)
1707859767.149 32103 32187 E AndroidRuntime: 	at m8.c.x(SourceFile:1)
1707859767.149 32103 32187 E AndroidRuntime: 	at m8.c.p(SourceFile:16)
1707859767.149 32103 32187 E AndroidRuntime: 	at m8.c.c(SourceFile:160)
1707859767.149 32103 32187 E AndroidRuntime: 	at n8.c.c(SourceFile:1620)
1707859767.149 32103 32187 E AndroidRuntime: 	at y.t.a(SourceFile:217)
1707859767.149 32103 32187 E AndroidRuntime: 	at y.t.b(SourceFile:19)
1707859767.149 32103 32187 E AndroidRuntime: 	at s1.w.run(SourceFile:28)
1707859767.149 32103 32187 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
1707859767.149 32103 32187 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: o8.c.<init> [class java.lang.String, class java.lang.String, class java.lang.String]
1707859767.149 32103 32187 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:3325)
1707859767.149 32103 32187 E AndroidRuntime: 	at java.lang.Class.getDeclaredConstructor(Class.java:3063)
1707859767.149 32103 32187 E AndroidRuntime: 	at j8.e.a(SourceFile:86)
1707859767.149 32103 32187 E AndroidRuntime: 	... 11 more
--------- switch to system
1707859767.209 32103 32103 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
--------- switch to main
1707859790.268 32326 32326 E ossify.messages: Not starting debugger since process cannot load the jdwp agent.
1707859790.395 32326 32326 E cutils-trace: Error opening trace file: No such file or directory (2)
1707859790.537 32326 32326 E org.fossify.messages: Unable to find pattern file or unable to map it for am
1707859790.854 32326 32356 E cutils-trace: Error opening trace file: No such file or directory (2)
--------- switch to system
1707859790.875 32326 32326 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
1707859792.359 32326 32326 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
--------- switch to crash
1707859792.460 32326 32414 E AndroidRuntime: FATAL EXCEPTION: Thread-14
1707859792.460 32326 32414 E AndroidRuntime: Process: org.fossify.messages, PID: 32326
1707859792.460 32326 32414 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodException: o8.c.<init> [class java.lang.String, class java.lang.String, class java.lang.String]
1707859792.460 32326 32414 E AndroidRuntime: 	at j8.e.a(SourceFile:117)
1707859792.460 32326 32414 E AndroidRuntime: 	at q8.a.c(SourceFile:37)
1707859792.460 32326 32414 E AndroidRuntime: 	at m8.h.l(SourceFile:8)
1707859792.460 32326 32414 E AndroidRuntime: 	at m8.c.y(SourceFile:40)
1707859792.460 32326 32414 E AndroidRuntime: 	at m8.c.x(SourceFile:1)
1707859792.460 32326 32414 E AndroidRuntime: 	at m8.c.p(SourceFile:16)
1707859792.460 32326 32414 E AndroidRuntime: 	at m8.c.c(SourceFile:160)
1707859792.460 32326 32414 E AndroidRuntime: 	at n8.c.c(SourceFile:1620)
1707859792.460 32326 32414 E AndroidRuntime: 	at y.t.a(SourceFile:217)
1707859792.460 32326 32414 E AndroidRuntime: 	at y.t.b(SourceFile:19)
1707859792.460 32326 32414 E AndroidRuntime: 	at s1.w.run(SourceFile:28)
1707859792.460 32326 32414 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
1707859792.460 32326 32414 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: o8.c.<init> [class java.lang.String, class java.lang.String, class java.lang.String]
1707859792.460 32326 32414 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:3325)
1707859792.460 32326 32414 E AndroidRuntime: 	at java.lang.Class.getDeclaredConstructor(Class.java:3063)
1707859792.460 32326 32414 E AndroidRuntime: 	at j8.e.a(SourceFile:86)
1707859792.460 32326 32414 E AndroidRuntime: 	... 11 more
```

**Comment by Aga-C** [comment]
If it also crashes other apps, especially Google Messages, we can't help with it, unfortunately. Maybe try posting in Discussions, so someone may think of some workaround, but there's nothing we can fix in Fossify Messages.

**Comment by ThatOneCalculator** [comment]
QKSMS was able to open it and I figured out what the problem was. I imported a bugged contact card and it had a last name suffix that was >1000 chars long 🤔
